from PIDPerfScripts.Binning import *
from PIDPerfScripts.Definitions import GetPartTypes
from PIDPerfScripts.Definitions import GetMuonPIDPartTypes

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'none', 0, 100000)
    AddBinScheme(  trType, 'PT', 'none', 0, 50000)
    AddBinScheme(  trType, 'nTracks', 'none', 0, 500)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'muons', 0, 100000)
    AddBinBoundary(trType, 'P',  'muons', 4000)
    AddBinBoundary(trType, 'P',  'muons', 8000)
    AddBinBoundary(trType, 'P',  'muons', 12000)
    AddBinBoundary(trType, 'P',  'muons', 16000)
    AddBinBoundary(trType, 'P',  'muons', 20000)
    AddBinBoundary(trType, 'P',  'muons', 24000)
    AddBinBoundary(trType, 'P',  'muons', 28000)
    AddBinBoundary(trType, 'P',  'muons', 30000)
    AddBinBoundary(trType, 'P',  'muons', 32000)
    AddBinBoundary(trType, 'P',  'muons', 34000)
    AddBinBoundary(trType, 'P',  'muons', 36000)
    AddBinBoundary(trType, 'P',  'muons', 38000)
    AddBinBoundary(trType, 'P',  'muons', 40000)
    AddBinBoundary(trType, 'P',  'muons', 42000)
    AddBinBoundary(trType, 'P',  'muons', 44000)
    AddBinBoundary(trType, 'P',  'muons', 46000)
    AddBinBoundary(trType, 'P',  'muons', 48000)
    AddBinBoundary(trType, 'P',  'muons', 50000)
    AddBinBoundary(trType, 'P',  'muons', 56000)
    AddBinBoundary(trType, 'P',  'muons', 64000)
    AddBinBoundary(trType, 'P',  'muons', 75000)
    AddBinBoundary(trType, 'P',  'muons', 90000)

    # pt
    AddBinScheme(  trType, 'PT', 'muons', 0, 50000)
    AddBinBoundary(trType, 'PT', 'muons', 1000)
    AddBinBoundary(trType, 'PT', 'muons', 1500)
    AddBinBoundary(trType, 'PT', 'muons', 2000)
    AddBinBoundary(trType, 'PT', 'muons', 2500)
    AddBinBoundary(trType, 'PT', 'muons', 3000)
    AddBinBoundary(trType, 'PT', 'muons', 5000)
    AddBinBoundary(trType, 'PT', 'muons', 7500)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'muons2', 0, 500000)
    AddBinBoundary(trType, 'P',  'muons2', 4000)
    AddBinBoundary(trType, 'P',  'muons2', 8000)
    AddBinBoundary(trType, 'P',  'muons2', 12000)
    AddBinBoundary(trType, 'P',  'muons2', 16000)
    AddBinBoundary(trType, 'P',  'muons2', 20000)
    AddBinBoundary(trType, 'P',  'muons2', 24000)
    AddBinBoundary(trType, 'P',  'muons2', 28000)
    AddBinBoundary(trType, 'P',  'muons2', 30000)
    AddBinBoundary(trType, 'P',  'muons2', 32000)
    AddBinBoundary(trType, 'P',  'muons2', 34000)
    AddBinBoundary(trType, 'P',  'muons2', 36000)
    AddBinBoundary(trType, 'P',  'muons2', 38000)
    AddBinBoundary(trType, 'P',  'muons2', 40000)
    AddBinBoundary(trType, 'P',  'muons2', 42000)
    AddBinBoundary(trType, 'P',  'muons2', 44000)
    AddBinBoundary(trType, 'P',  'muons2', 46000)
    AddBinBoundary(trType, 'P',  'muons2', 48000)
    AddBinBoundary(trType, 'P',  'muons2', 50000)
    AddBinBoundary(trType, 'P',  'muons2', 56000)
    AddBinBoundary(trType, 'P',  'muons2', 64000)
    AddBinBoundary(trType, 'P',  'muons2', 75000)
    AddBinBoundary(trType, 'P',  'muons2', 90000)
    AddBinBoundary(trType, 'P',  'muons2',120000)
    AddBinBoundary(trType, 'P',  'muons2',150000)
    AddBinBoundary(trType, 'P',  'muons2',200000)
    AddBinBoundary(trType, 'P',  'muons2',250000)
    AddBinBoundary(trType, 'P',  'muons2',300000)
    AddBinBoundary(trType, 'P',  'muons2',400000)

    # pt
    AddBinScheme(  trType, 'PT', 'muons2', 0, 50000)
    AddBinBoundary(trType, 'PT', 'muons2', 1000)
    AddBinBoundary(trType, 'PT', 'muons2', 1500)
    AddBinBoundary(trType, 'PT', 'muons2', 2000)
    AddBinBoundary(trType, 'PT', 'muons2', 2500)
    AddBinBoundary(trType, 'PT', 'muons2', 3000)
    AddBinBoundary(trType, 'PT', 'muons2', 5000)
    AddBinBoundary(trType, 'PT', 'muons2', 7500)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'muons3', 0, 500000)
    AddBinBoundary(trType, 'P',  'muons3', 4000)
    AddBinBoundary(trType, 'P',  'muons3', 8000)
    AddBinBoundary(trType, 'P',  'muons3', 12000)
    AddBinBoundary(trType, 'P',  'muons3', 16000)
    AddBinBoundary(trType, 'P',  'muons3', 20000)
    AddBinBoundary(trType, 'P',  'muons3', 24000)
    AddBinBoundary(trType, 'P',  'muons3', 28000)
    AddBinBoundary(trType, 'P',  'muons3', 32000)
    AddBinBoundary(trType, 'P',  'muons3', 36000)
    AddBinBoundary(trType, 'P',  'muons3', 40000)
    AddBinBoundary(trType, 'P',  'muons3', 44000)
    AddBinBoundary(trType, 'P',  'muons3', 50000)
    AddBinBoundary(trType, 'P',  'muons3', 56000)
    AddBinBoundary(trType, 'P',  'muons3', 64000)
    AddBinBoundary(trType, 'P',  'muons3', 75000)
    AddBinBoundary(trType, 'P',  'muons3', 90000)
    AddBinBoundary(trType, 'P',  'muons3',120000)
    AddBinBoundary(trType, 'P',  'muons3',150000)
    AddBinBoundary(trType, 'P',  'muons3',200000)
    AddBinBoundary(trType, 'P',  'muons3',250000)
    AddBinBoundary(trType, 'P',  'muons3',300000)
    AddBinBoundary(trType, 'P',  'muons3',400000)

    # pt
    AddBinScheme(  trType, 'PT', 'muons3', 0, 50000)
    AddBinBoundary(trType, 'PT', 'muons3', 1000)
    AddBinBoundary(trType, 'PT', 'muons3', 1500)
    AddBinBoundary(trType, 'PT', 'muons3', 2000)
    AddBinBoundary(trType, 'PT', 'muons3', 2500)
    AddBinBoundary(trType, 'PT', 'muons3', 3000)
    AddBinBoundary(trType, 'PT', 'muons3', 5000)
    AddBinBoundary(trType, 'PT', 'muons3', 7500)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'muons4', 0, 500000)
    AddBinBoundary(trType, 'P',  'muons4', 4000)
    AddBinBoundary(trType, 'P',  'muons4', 8000)
    AddBinBoundary(trType, 'P',  'muons4', 12000)
    AddBinBoundary(trType, 'P',  'muons4', 16000)
    AddBinBoundary(trType, 'P',  'muons4', 20000)
    AddBinBoundary(trType, 'P',  'muons4', 24000)
    AddBinBoundary(trType, 'P',  'muons4', 28000)
    AddBinBoundary(trType, 'P',  'muons4', 32000)
    AddBinBoundary(trType, 'P',  'muons4', 36000)
    AddBinBoundary(trType, 'P',  'muons4', 40000)
    AddBinBoundary(trType, 'P',  'muons4', 44000)
    AddBinBoundary(trType, 'P',  'muons4', 50000)
    AddBinBoundary(trType, 'P',  'muons4', 56000)
    AddBinBoundary(trType, 'P',  'muons4', 64000)
    AddBinBoundary(trType, 'P',  'muons4', 75000)
    AddBinBoundary(trType, 'P',  'muons4', 90000)
    AddBinBoundary(trType, 'P',  'muons4',120000)
    AddBinBoundary(trType, 'P',  'muons4',150000)
    AddBinBoundary(trType, 'P',  'muons4',200000)
    AddBinBoundary(trType, 'P',  'muons4',250000)
    AddBinBoundary(trType, 'P',  'muons4',300000)
    AddBinBoundary(trType, 'P',  'muons4',400000)

    # pt
    AddBinScheme(  trType, 'PT', 'muons4', 0, 50000)
    AddBinBoundary(trType, 'PT', 'muons4', 1000)
    AddBinBoundary(trType, 'PT', 'muons4', 1100)
    AddBinBoundary(trType, 'PT', 'muons4', 1200)
    AddBinBoundary(trType, 'PT', 'muons4', 1300)
    AddBinBoundary(trType, 'PT', 'muons4', 1400)
    AddBinBoundary(trType, 'PT', 'muons4', 1500)
    AddBinBoundary(trType, 'PT', 'muons4', 1600)
    AddBinBoundary(trType, 'PT', 'muons4', 1700)
    AddBinBoundary(trType, 'PT', 'muons4', 1800)
    AddBinBoundary(trType, 'PT', 'muons4', 1900)
    AddBinBoundary(trType, 'PT', 'muons4', 2000)
    AddBinBoundary(trType, 'PT', 'muons4', 2250)
    AddBinBoundary(trType, 'PT', 'muons4', 2500)
    AddBinBoundary(trType, 'PT', 'muons4', 2750)
    AddBinBoundary(trType, 'PT', 'muons4', 3000)
    AddBinBoundary(trType, 'PT', 'muons4', 3500)
    AddBinBoundary(trType, 'PT', 'muons4', 4000)
    AddBinBoundary(trType, 'PT', 'muons4', 4500)
    AddBinBoundary(trType, 'PT', 'muons4', 5000)
    AddBinBoundary(trType, 'PT', 'muons4', 6250)
    AddBinBoundary(trType, 'PT', 'muons4', 7500)
    AddBinBoundary(trType, 'PT', 'muons4',10000)
    AddBinBoundary(trType, 'PT', 'muons4',20000)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'muons5', 0, 500000)
    AddBinBoundary(trType, 'P',  'muons5', 4000)
    AddBinBoundary(trType, 'P',  'muons5', 8000)
    AddBinBoundary(trType, 'P',  'muons5', 12000)
    AddBinBoundary(trType, 'P',  'muons5', 16000)
    AddBinBoundary(trType, 'P',  'muons5', 20000)
    AddBinBoundary(trType, 'P',  'muons5', 24000)
    AddBinBoundary(trType, 'P',  'muons5', 28000)
    AddBinBoundary(trType, 'P',  'muons5', 32000)
    AddBinBoundary(trType, 'P',  'muons5', 36000)
    AddBinBoundary(trType, 'P',  'muons5', 40000)
    AddBinBoundary(trType, 'P',  'muons5', 44000)
    AddBinBoundary(trType, 'P',  'muons5', 50000)
    AddBinBoundary(trType, 'P',  'muons5', 56000)
    AddBinBoundary(trType, 'P',  'muons5', 64000)
    AddBinBoundary(trType, 'P',  'muons5', 75000)
    AddBinBoundary(trType, 'P',  'muons5', 90000)
    AddBinBoundary(trType, 'P',  'muons5',120000)
    AddBinBoundary(trType, 'P',  'muons5',150000)
    AddBinBoundary(trType, 'P',  'muons5',200000)
    AddBinBoundary(trType, 'P',  'muons5',250000)
    AddBinBoundary(trType, 'P',  'muons5',300000)
    AddBinBoundary(trType, 'P',  'muons5',400000)
    AddBinScheme(  trType, 'Brunel_P',  'muons5', 0, 500000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 4000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 12000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 44000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 56000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 64000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 75000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5', 90000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5',120000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5',150000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5',200000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5',250000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5',300000)
    AddBinBoundary(trType, 'Brunel_P',  'muons5',400000)

    # pt
    AddBinScheme(  trType, 'PT', 'muons5', 0, 50000)
    AddBinBoundary(trType, 'PT', 'muons5', 1000)
    AddBinBoundary(trType, 'PT', 'muons5', 1100)
    AddBinBoundary(trType, 'PT', 'muons5', 1200)
    AddBinBoundary(trType, 'PT', 'muons5', 1300)
    AddBinBoundary(trType, 'PT', 'muons5', 1400)
    AddBinBoundary(trType, 'PT', 'muons5', 1500)
    AddBinBoundary(trType, 'PT', 'muons5', 1600)
    AddBinBoundary(trType, 'PT', 'muons5', 1700)
    AddBinBoundary(trType, 'PT', 'muons5', 1800)
    AddBinBoundary(trType, 'PT', 'muons5', 1900)
    AddBinBoundary(trType, 'PT', 'muons5', 2000)
    AddBinBoundary(trType, 'PT', 'muons5', 2250)
    AddBinBoundary(trType, 'PT', 'muons5', 2500)
    AddBinBoundary(trType, 'PT', 'muons5', 2750)
    AddBinBoundary(trType, 'PT', 'muons5', 3000)
    AddBinBoundary(trType, 'PT', 'muons5', 3500)
    AddBinBoundary(trType, 'PT', 'muons5', 4000)
    AddBinBoundary(trType, 'PT', 'muons5', 4500)
    AddBinBoundary(trType, 'PT', 'muons5', 5000)
    AddBinBoundary(trType, 'PT', 'muons5', 6250)
    AddBinBoundary(trType, 'PT', 'muons5', 7500)
    AddBinBoundary(trType, 'PT', 'muons5',10000)
    AddBinBoundary(trType, 'PT', 'muons5',20000)
    AddBinScheme(  trType, 'Brunel_PT', 'muons5', 0, 50000)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1100)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1200)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1300)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1400)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1600)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1700)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1800)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 1900)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 2250)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 2500)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 2750)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 3000)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 3500)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 4500)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 5000)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 6250)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5', 7500)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5',10000)
    AddBinBoundary(trType, 'Brunel_PT', 'muons5',20000)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'muons5', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'muons5', 120)
    AddBinBoundary(trType, 'nTracks', 'muons5', 180)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'muonsalt', 0, 500000)
    AddBinBoundary(trType, 'P',  'muonsalt', 8000)
    AddBinBoundary(trType, 'P',  'muonsalt', 16000)
    AddBinBoundary(trType, 'P',  'muonsalt', 24000)
    AddBinBoundary(trType, 'P',  'muonsalt', 32000)
    AddBinBoundary(trType, 'P',  'muonsalt', 40000)
    AddBinBoundary(trType, 'P',  'muonsalt', 50000)
    AddBinBoundary(trType, 'P',  'muonsalt', 64000)
    AddBinBoundary(trType, 'P',  'muonsalt', 90000)
    AddBinBoundary(trType, 'P',  'muonsalt',150000)
    AddBinBoundary(trType, 'P',  'muonsalt',250000)
    AddBinBoundary(trType, 'P',  'muonsalt',400000)

    # pt
    AddBinScheme(  trType, 'PT', 'muonsalt', 0, 50000)
    AddBinBoundary(trType, 'PT', 'muonsalt', 1000)
    AddBinBoundary(trType, 'PT', 'muonsalt', 1200)
    AddBinBoundary(trType, 'PT', 'muonsalt', 1400)
    AddBinBoundary(trType, 'PT', 'muonsalt', 1600)
    AddBinBoundary(trType, 'PT', 'muonsalt', 1800)
    AddBinBoundary(trType, 'PT', 'muonsalt', 2000)
    AddBinBoundary(trType, 'PT', 'muonsalt', 2500)
    AddBinBoundary(trType, 'PT', 'muonsalt', 3000)
    AddBinBoundary(trType, 'PT', 'muonsalt', 4000)
    AddBinBoundary(trType, 'PT', 'muonsalt', 5000)
    AddBinBoundary(trType, 'PT', 'muonsalt', 7500)
    AddBinBoundary(trType, 'PT', 'muonsalt',20000)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'muonsalt', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'muonsalt',  60)
    AddBinBoundary(trType, 'nTracks', 'muonsalt', 120)
    AddBinBoundary(trType, 'nTracks', 'muonsalt', 180)
    AddBinBoundary(trType, 'nTracks', 'muonsalt', 240)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'kaons', 0, 500000)
    AddBinBoundary(trType, 'P',  'kaons', 4000)
    AddBinBoundary(trType, 'P',  'kaons', 8000)
    AddBinBoundary(trType, 'P',  'kaons', 12000)
    AddBinBoundary(trType, 'P',  'kaons', 16000)
    AddBinBoundary(trType, 'P',  'kaons', 20000)
    AddBinBoundary(trType, 'P',  'kaons', 24000)
    AddBinBoundary(trType, 'P',  'kaons', 28000)
    AddBinBoundary(trType, 'P',  'kaons', 32000)
    AddBinBoundary(trType, 'P',  'kaons', 36000)
    AddBinBoundary(trType, 'P',  'kaons', 40000)
    AddBinBoundary(trType, 'P',  'kaons', 44000)
    AddBinBoundary(trType, 'P',  'kaons', 50000)
    AddBinBoundary(trType, 'P',  'kaons', 56000)
    AddBinBoundary(trType, 'P',  'kaons', 64000)
    AddBinBoundary(trType, 'P',  'kaons', 75000)
    AddBinBoundary(trType, 'P',  'kaons', 90000)
    AddBinBoundary(trType, 'P',  'kaons',120000)
    AddBinBoundary(trType, 'P',  'kaons',150000)
    AddBinBoundary(trType, 'P',  'kaons',200000)
    AddBinBoundary(trType, 'P',  'kaons',250000)
    AddBinBoundary(trType, 'P',  'kaons',300000)
    AddBinBoundary(trType, 'P',  'kaons',400000)

    # pt
    AddBinScheme(  trType, 'PT', 'kaons', 0, 50000)
    AddBinBoundary(trType, 'PT', 'kaons', 1000)
    AddBinBoundary(trType, 'PT', 'kaons', 1100)
    AddBinBoundary(trType, 'PT', 'kaons', 1200)
    AddBinBoundary(trType, 'PT', 'kaons', 1300)
    AddBinBoundary(trType, 'PT', 'kaons', 1400)
    AddBinBoundary(trType, 'PT', 'kaons', 1500)
    AddBinBoundary(trType, 'PT', 'kaons', 1600)
    AddBinBoundary(trType, 'PT', 'kaons', 1700)
    AddBinBoundary(trType, 'PT', 'kaons', 1800)
    AddBinBoundary(trType, 'PT', 'kaons', 1900)
    AddBinBoundary(trType, 'PT', 'kaons', 2000)
    AddBinBoundary(trType, 'PT', 'kaons', 2250)
    AddBinBoundary(trType, 'PT', 'kaons', 2500)
    AddBinBoundary(trType, 'PT', 'kaons', 2750)
    AddBinBoundary(trType, 'PT', 'kaons', 3000)
    AddBinBoundary(trType, 'PT', 'kaons', 3500)
    AddBinBoundary(trType, 'PT', 'kaons', 4000)
    AddBinBoundary(trType, 'PT', 'kaons', 4500)
    AddBinBoundary(trType, 'PT', 'kaons', 5000)
    AddBinBoundary(trType, 'PT', 'kaons', 6250)
    AddBinBoundary(trType, 'PT', 'kaons', 7500)
    AddBinBoundary(trType, 'PT', 'kaons',10000)
    AddBinBoundary(trType, 'PT', 'kaons',20000)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'kaons2', 0, 160000)
    AddBinBoundary(trType, 'P',  'kaons2', 4000)
    AddBinBoundary(trType, 'P',  'kaons2', 8000)
    AddBinBoundary(trType, 'P',  'kaons2', 12000)
    AddBinBoundary(trType, 'P',  'kaons2', 16000)
    AddBinBoundary(trType, 'P',  'kaons2', 20000)
    AddBinBoundary(trType, 'P',  'kaons2', 24000)
    AddBinBoundary(trType, 'P',  'kaons2', 28000)
    AddBinBoundary(trType, 'P',  'kaons2', 32000)
    AddBinBoundary(trType, 'P',  'kaons2', 36000)
    AddBinBoundary(trType, 'P',  'kaons2', 40000)
    AddBinBoundary(trType, 'P',  'kaons2', 44000)
    AddBinBoundary(trType, 'P',  'kaons2', 50000)
    AddBinBoundary(trType, 'P',  'kaons2', 56000)
    AddBinBoundary(trType, 'P',  'kaons2', 64000)
    AddBinBoundary(trType, 'P',  'kaons2', 75000)
    AddBinBoundary(trType, 'P',  'kaons2', 90000)
    AddBinBoundary(trType, 'P',  'kaons2',120000)

    # pt
    AddBinScheme(  trType, 'PT', 'kaons2', 0, 20000)
    AddBinBoundary(trType, 'PT', 'kaons2', 1000)
    AddBinBoundary(trType, 'PT', 'kaons2', 1100)
    AddBinBoundary(trType, 'PT', 'kaons2', 1200)
    AddBinBoundary(trType, 'PT', 'kaons2', 1300)
    AddBinBoundary(trType, 'PT', 'kaons2', 1400)
    AddBinBoundary(trType, 'PT', 'kaons2', 1500)
    AddBinBoundary(trType, 'PT', 'kaons2', 1600)
    AddBinBoundary(trType, 'PT', 'kaons2', 1700)
    AddBinBoundary(trType, 'PT', 'kaons2', 1800)
    AddBinBoundary(trType, 'PT', 'kaons2', 1900)
    AddBinBoundary(trType, 'PT', 'kaons2', 2000)
    AddBinBoundary(trType, 'PT', 'kaons2', 2250)
    AddBinBoundary(trType, 'PT', 'kaons2', 2500)
    AddBinBoundary(trType, 'PT', 'kaons2', 2750)
    AddBinBoundary(trType, 'PT', 'kaons2', 3000)
    AddBinBoundary(trType, 'PT', 'kaons2', 3500)
    AddBinBoundary(trType, 'PT', 'kaons2', 4000)
    AddBinBoundary(trType, 'PT', 'kaons2', 4500)
    AddBinBoundary(trType, 'PT', 'kaons2', 5000)
    AddBinBoundary(trType, 'PT', 'kaons2', 6250)
    AddBinBoundary(trType, 'PT', 'kaons2', 7500)
    AddBinBoundary(trType, 'PT', 'kaons2',10000)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'Brunel_P',  'kaons3', 0, 160000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 4000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 12000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 44000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 56000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 64000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 75000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3', 90000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons3',120000)

    # pt
    AddBinScheme(  trType, 'Brunel_PT', 'kaons3', 0, 20000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1100)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1200)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1300)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1400)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1600)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1700)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1800)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 1900)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 2250)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 2500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 2750)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 3000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 3500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 4500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 5000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 6250)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3', 7500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons3',10000)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'kaons3', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'kaons3', 120)
    AddBinBoundary(trType, 'nTracks', 'kaons3', 180)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'Brunel_P',  'kaons4', 0, 500000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 4000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 12000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 44000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 56000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 64000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 75000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4', 90000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4',120000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4',160000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4',250000)
    AddBinBoundary(trType, 'Brunel_P',  'kaons4',350000)

    # pt
    AddBinScheme(  trType, 'Brunel_PT', 'kaons4', 0, 50000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1100)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1200)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1300)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1400)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1600)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1700)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1800)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 1900)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 2250)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 2500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 2750)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 3000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 3500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 4500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 5000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 6250)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4', 7500)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4',10000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4',15000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4',25000)
    AddBinBoundary(trType, 'Brunel_PT', 'kaons4',35000)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'kaons4', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'kaons4', 120)
    AddBinBoundary(trType, 'nTracks', 'kaons4', 180)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'kaonsalt', 0, 160000)
    AddBinBoundary(trType, 'P',  'kaonsalt', 8000)
    AddBinBoundary(trType, 'P',  'kaonsalt', 16000)
    AddBinBoundary(trType, 'P',  'kaonsalt', 24000)
    AddBinBoundary(trType, 'P',  'kaonsalt', 32000)
    AddBinBoundary(trType, 'P',  'kaonsalt', 40000)
    AddBinBoundary(trType, 'P',  'kaonsalt', 50000)
    AddBinBoundary(trType, 'P',  'kaonsalt', 64000)
    AddBinBoundary(trType, 'P',  'kaonsalt', 90000)

    # pt
    AddBinScheme(  trType, 'PT', 'kaonsalt', 0, 20000)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 1000)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 1200)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 1400)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 1600)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 1800)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 2000)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 2500)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 3000)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 4000)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 5000)
    AddBinBoundary(trType, 'PT', 'kaonsalt', 7500)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'kaonsalt', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'kaonsalt',  60)
    AddBinBoundary(trType, 'nTracks', 'kaonsalt', 120)
    AddBinBoundary(trType, 'nTracks', 'kaonsalt', 180)
    AddBinBoundary(trType, 'nTracks', 'kaonsalt', 240)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'protons', 0, 500000)
    AddBinBoundary(trType, 'P',  'protons', 4000)
    AddBinBoundary(trType, 'P',  'protons', 8000)
    AddBinBoundary(trType, 'P',  'protons', 12000)
    AddBinBoundary(trType, 'P',  'protons', 16000)
    AddBinBoundary(trType, 'P',  'protons', 20000)
    AddBinBoundary(trType, 'P',  'protons', 24000)
    AddBinBoundary(trType, 'P',  'protons', 28000)
    AddBinBoundary(trType, 'P',  'protons', 32000)
    AddBinBoundary(trType, 'P',  'protons', 36000)
    AddBinBoundary(trType, 'P',  'protons', 40000)
    AddBinBoundary(trType, 'P',  'protons', 44000)
    AddBinBoundary(trType, 'P',  'protons', 50000)
    AddBinBoundary(trType, 'P',  'protons', 56000)
    AddBinBoundary(trType, 'P',  'protons', 64000)
    AddBinBoundary(trType, 'P',  'protons', 75000)
    AddBinBoundary(trType, 'P',  'protons', 90000)
    AddBinBoundary(trType, 'P',  'protons',120000)
    AddBinBoundary(trType, 'P',  'protons',150000)
    AddBinBoundary(trType, 'P',  'protons',200000)
    AddBinBoundary(trType, 'P',  'protons',250000)
    AddBinBoundary(trType, 'P',  'protons',300000)
    AddBinBoundary(trType, 'P',  'protons',400000)

    # pt
    AddBinScheme(  trType, 'PT', 'protons', 0, 50000)
    AddBinBoundary(trType, 'PT', 'protons', 1000)
    AddBinBoundary(trType, 'PT', 'protons', 1100)
    AddBinBoundary(trType, 'PT', 'protons', 1200)
    AddBinBoundary(trType, 'PT', 'protons', 1300)
    AddBinBoundary(trType, 'PT', 'protons', 1400)
    AddBinBoundary(trType, 'PT', 'protons', 1500)
    AddBinBoundary(trType, 'PT', 'protons', 1600)
    AddBinBoundary(trType, 'PT', 'protons', 1700)
    AddBinBoundary(trType, 'PT', 'protons', 1800)
    AddBinBoundary(trType, 'PT', 'protons', 1900)
    AddBinBoundary(trType, 'PT', 'protons', 2000)
    AddBinBoundary(trType, 'PT', 'protons', 2250)
    AddBinBoundary(trType, 'PT', 'protons', 2500)
    AddBinBoundary(trType, 'PT', 'protons', 2750)
    AddBinBoundary(trType, 'PT', 'protons', 3000)
    AddBinBoundary(trType, 'PT', 'protons', 3500)
    AddBinBoundary(trType, 'PT', 'protons', 4000)
    AddBinBoundary(trType, 'PT', 'protons', 4500)
    AddBinBoundary(trType, 'PT', 'protons', 5000)
    AddBinBoundary(trType, 'PT', 'protons', 6250)
    AddBinBoundary(trType, 'PT', 'protons', 7500)
    AddBinBoundary(trType, 'PT', 'protons',10000)
    AddBinBoundary(trType, 'PT', 'protons',20000)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'protons2', 0, 160000)
    AddBinBoundary(trType, 'P',  'protons2', 4000)
    AddBinBoundary(trType, 'P',  'protons2', 8000)
    AddBinBoundary(trType, 'P',  'protons2', 12000)
    AddBinBoundary(trType, 'P',  'protons2', 16000)
    AddBinBoundary(trType, 'P',  'protons2', 20000)
    AddBinBoundary(trType, 'P',  'protons2', 24000)
    AddBinBoundary(trType, 'P',  'protons2', 28000)
    AddBinBoundary(trType, 'P',  'protons2', 32000)
    AddBinBoundary(trType, 'P',  'protons2', 36000)
    AddBinBoundary(trType, 'P',  'protons2', 40000)
    AddBinBoundary(trType, 'P',  'protons2', 44000)
    AddBinBoundary(trType, 'P',  'protons2', 50000)
    AddBinBoundary(trType, 'P',  'protons2', 56000)
    AddBinBoundary(trType, 'P',  'protons2', 64000)
    AddBinBoundary(trType, 'P',  'protons2', 75000)
    AddBinBoundary(trType, 'P',  'protons2', 90000)
    AddBinBoundary(trType, 'P',  'protons2',120000)

    # pt
    AddBinScheme(  trType, 'PT', 'protons2', 0, 20000)
    AddBinBoundary(trType, 'PT', 'protons2', 1000)
    AddBinBoundary(trType, 'PT', 'protons2', 1100)
    AddBinBoundary(trType, 'PT', 'protons2', 1200)
    AddBinBoundary(trType, 'PT', 'protons2', 1300)
    AddBinBoundary(trType, 'PT', 'protons2', 1400)
    AddBinBoundary(trType, 'PT', 'protons2', 1500)
    AddBinBoundary(trType, 'PT', 'protons2', 1600)
    AddBinBoundary(trType, 'PT', 'protons2', 1700)
    AddBinBoundary(trType, 'PT', 'protons2', 1800)
    AddBinBoundary(trType, 'PT', 'protons2', 1900)
    AddBinBoundary(trType, 'PT', 'protons2', 2000)
    AddBinBoundary(trType, 'PT', 'protons2', 2250)
    AddBinBoundary(trType, 'PT', 'protons2', 2500)
    AddBinBoundary(trType, 'PT', 'protons2', 2750)
    AddBinBoundary(trType, 'PT', 'protons2', 3000)
    AddBinBoundary(trType, 'PT', 'protons2', 3500)
    AddBinBoundary(trType, 'PT', 'protons2', 4000)
    AddBinBoundary(trType, 'PT', 'protons2', 4500)
    AddBinBoundary(trType, 'PT', 'protons2', 5000)
    AddBinBoundary(trType, 'PT', 'protons2', 6250)
    AddBinBoundary(trType, 'PT', 'protons2', 7500)
    AddBinBoundary(trType, 'PT', 'protons2',10000)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'protons3', 0, 160000)
    AddBinBoundary(trType, 'P',  'protons3', 4000)
    AddBinBoundary(trType, 'P',  'protons3', 8000)
    AddBinBoundary(trType, 'P',  'protons3', 12000)
    AddBinBoundary(trType, 'P',  'protons3', 16000)
    AddBinBoundary(trType, 'P',  'protons3', 20000)
    AddBinBoundary(trType, 'P',  'protons3', 24000)
    AddBinBoundary(trType, 'P',  'protons3', 28000)
    AddBinBoundary(trType, 'P',  'protons3', 32000)
    AddBinBoundary(trType, 'P',  'protons3', 36000)
    AddBinBoundary(trType, 'P',  'protons3', 40000)
    AddBinBoundary(trType, 'P',  'protons3', 50000)
    AddBinBoundary(trType, 'P',  'protons3', 80000)
    AddBinBoundary(trType, 'P',  'protons3',120000)

    # pt
    AddBinScheme(  trType, 'PT', 'protons3', 0, 20000)
    AddBinBoundary(trType, 'PT', 'protons3', 1000)
    AddBinBoundary(trType, 'PT', 'protons3', 1250)
    AddBinBoundary(trType, 'PT', 'protons3', 1500)
    AddBinBoundary(trType, 'PT', 'protons3', 1750)
    AddBinBoundary(trType, 'PT', 'protons3', 2000)
    AddBinBoundary(trType, 'PT', 'protons3', 2500)
    AddBinBoundary(trType, 'PT', 'protons3', 4000)
    AddBinBoundary(trType, 'PT', 'protons3', 7500)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'protons4', 0, 160000)
    AddBinBoundary(trType, 'P',  'protons4', 4000)
    AddBinBoundary(trType, 'P',  'protons4', 8000)
    AddBinBoundary(trType, 'P',  'protons4', 12000)
    AddBinBoundary(trType, 'P',  'protons4', 16000)
    AddBinBoundary(trType, 'P',  'protons4', 18000)
    AddBinBoundary(trType, 'P',  'protons4', 20000)
    AddBinBoundary(trType, 'P',  'protons4', 22000)
    AddBinBoundary(trType, 'P',  'protons4', 24000)
    AddBinBoundary(trType, 'P',  'protons4', 28000)
    AddBinBoundary(trType, 'P',  'protons4', 32000)
    AddBinBoundary(trType, 'P',  'protons4', 36000)
    AddBinBoundary(trType, 'P',  'protons4', 40000)
    AddBinBoundary(trType, 'P',  'protons4', 50000)
    AddBinBoundary(trType, 'P',  'protons4', 60000)
    AddBinBoundary(trType, 'P',  'protons4', 80000)
    AddBinBoundary(trType, 'P',  'protons4',120000)

    # pt
    AddBinScheme(  trType, 'PT', 'protons4', 0, 20000)
    AddBinBoundary(trType, 'PT', 'protons4',  750)
    AddBinBoundary(trType, 'PT', 'protons4',  900)
    AddBinBoundary(trType, 'PT', 'protons4', 1000)
    AddBinBoundary(trType, 'PT', 'protons4', 1100)
    AddBinBoundary(trType, 'PT', 'protons4', 1250)
    AddBinBoundary(trType, 'PT', 'protons4', 1500)
    AddBinBoundary(trType, 'PT', 'protons4', 1750)
    AddBinBoundary(trType, 'PT', 'protons4', 2000)
    AddBinBoundary(trType, 'PT', 'protons4', 2500)
    AddBinBoundary(trType, 'PT', 'protons4', 4000)
    AddBinBoundary(trType, 'PT', 'protons4', 7500)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'protons5', 0, 160000)
    AddBinBoundary(trType, 'P',  'protons5', 4000)
    AddBinBoundary(trType, 'P',  'protons5', 8000)
    AddBinBoundary(trType, 'P',  'protons5', 12000)
    AddBinBoundary(trType, 'P',  'protons5', 16000)
    AddBinBoundary(trType, 'P',  'protons5', 18000)
    AddBinBoundary(trType, 'P',  'protons5', 19000)
    AddBinBoundary(trType, 'P',  'protons5', 20000)
    AddBinBoundary(trType, 'P',  'protons5', 21000)
    AddBinBoundary(trType, 'P',  'protons5', 22000)
    AddBinBoundary(trType, 'P',  'protons5', 23000)
    AddBinBoundary(trType, 'P',  'protons5', 24000)
    AddBinBoundary(trType, 'P',  'protons5', 26000)
    AddBinBoundary(trType, 'P',  'protons5', 28000)
    AddBinBoundary(trType, 'P',  'protons5', 30000)
    AddBinBoundary(trType, 'P',  'protons5', 32000)
    AddBinBoundary(trType, 'P',  'protons5', 34000)
    AddBinBoundary(trType, 'P',  'protons5', 36000)
    AddBinBoundary(trType, 'P',  'protons5', 40000)
    AddBinBoundary(trType, 'P',  'protons5', 45000)
    AddBinBoundary(trType, 'P',  'protons5', 50000)
    AddBinBoundary(trType, 'P',  'protons5', 55000)
    AddBinBoundary(trType, 'P',  'protons5', 60000)
    AddBinBoundary(trType, 'P',  'protons5', 70000)
    AddBinBoundary(trType, 'P',  'protons5', 80000)
    AddBinBoundary(trType, 'P',  'protons5',120000)

    # pt
    AddBinScheme(  trType, 'PT', 'protons5', 0, 20000)
    AddBinBoundary(trType, 'PT', 'protons5',  750)
    AddBinBoundary(trType, 'PT', 'protons5',  900)
    AddBinBoundary(trType, 'PT', 'protons5', 1000)
    AddBinBoundary(trType, 'PT', 'protons5', 1100)
    AddBinBoundary(trType, 'PT', 'protons5', 1250)
    AddBinBoundary(trType, 'PT', 'protons5', 1500)
    AddBinBoundary(trType, 'PT', 'protons5', 1750)
    AddBinBoundary(trType, 'PT', 'protons5', 2000)
    AddBinBoundary(trType, 'PT', 'protons5', 2500)
    AddBinBoundary(trType, 'PT', 'protons5', 4000)
    AddBinBoundary(trType, 'PT', 'protons5', 7500)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'protons6', 0, 160000)
    AddBinBoundary(trType, 'P',  'protons6', 4000)
    AddBinBoundary(trType, 'P',  'protons6', 8000)
    AddBinBoundary(trType, 'P',  'protons6', 12000)
    AddBinBoundary(trType, 'P',  'protons6', 16000)
    AddBinBoundary(trType, 'P',  'protons6', 18000)
    AddBinBoundary(trType, 'P',  'protons6', 19000)
    AddBinBoundary(trType, 'P',  'protons6', 20000)
    AddBinBoundary(trType, 'P',  'protons6', 21000)
    AddBinBoundary(trType, 'P',  'protons6', 22000)
    AddBinBoundary(trType, 'P',  'protons6', 23000)
    AddBinBoundary(trType, 'P',  'protons6', 24000)
    AddBinBoundary(trType, 'P',  'protons6', 26000)
    AddBinBoundary(trType, 'P',  'protons6', 28000)
    AddBinBoundary(trType, 'P',  'protons6', 30000)
    AddBinBoundary(trType, 'P',  'protons6', 32000)
    AddBinBoundary(trType, 'P',  'protons6', 34000)
    AddBinBoundary(trType, 'P',  'protons6', 36000)
    AddBinBoundary(trType, 'P',  'protons6', 40000)
    AddBinBoundary(trType, 'P',  'protons6', 45000)
    AddBinBoundary(trType, 'P',  'protons6', 50000)
    AddBinBoundary(trType, 'P',  'protons6', 55000)
    AddBinBoundary(trType, 'P',  'protons6', 60000)
    AddBinBoundary(trType, 'P',  'protons6', 70000)
    AddBinBoundary(trType, 'P',  'protons6', 80000)
    AddBinBoundary(trType, 'P',  'protons6',120000)

    AddBinScheme(  trType, 'Brunel_P',  'protons6', 0, 160000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 4000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 12000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 18000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 19000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 21000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 22000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 23000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 26000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 30000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 34000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 45000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 55000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 60000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 70000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6', 80000)
    AddBinBoundary(trType, 'Brunel_P',  'protons6',120000)

    # pt
    AddBinScheme(  trType, 'PT', 'protons6', 0, 20000)
    AddBinBoundary(trType, 'PT', 'protons6',  750)
    AddBinBoundary(trType, 'PT', 'protons6',  900)
    AddBinBoundary(trType, 'PT', 'protons6', 1000)
    AddBinBoundary(trType, 'PT', 'protons6', 1100)
    AddBinBoundary(trType, 'PT', 'protons6', 1250)
    AddBinBoundary(trType, 'PT', 'protons6', 1500)
    AddBinBoundary(trType, 'PT', 'protons6', 1750)
    AddBinBoundary(trType, 'PT', 'protons6', 2000)
    AddBinBoundary(trType, 'PT', 'protons6', 2500)
    AddBinBoundary(trType, 'PT', 'protons6', 4000)
    AddBinBoundary(trType, 'PT', 'protons6', 7500)

    AddBinScheme(  trType, 'Brunel_PT', 'protons6', 0, 20000)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6',  750)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6',  900)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 1100)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 1250)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 1750)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 2500)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'protons6', 7500)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'protons6', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'protons6', 120)
    AddBinBoundary(trType, 'nTracks', 'protons6', 180)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'P',  'protonsalt', 0, 160000)
    AddBinBoundary(trType, 'P',  'protonsalt', 8000)
    AddBinBoundary(trType, 'P',  'protonsalt', 16000)
    AddBinBoundary(trType, 'P',  'protonsalt', 19000)
    AddBinBoundary(trType, 'P',  'protonsalt', 21000)
    AddBinBoundary(trType, 'P',  'protonsalt', 23000)
    AddBinBoundary(trType, 'P',  'protonsalt', 26000)
    AddBinBoundary(trType, 'P',  'protonsalt', 30000)
    AddBinBoundary(trType, 'P',  'protonsalt', 34000)
    AddBinBoundary(trType, 'P',  'protonsalt', 40000)
    AddBinBoundary(trType, 'P',  'protonsalt', 50000)
    AddBinBoundary(trType, 'P',  'protonsalt', 60000)
    AddBinBoundary(trType, 'P',  'protonsalt', 80000)

    # pt
    AddBinScheme(  trType, 'PT', 'protonsalt', 0, 20000)
    AddBinBoundary(trType, 'PT', 'protonsalt', 1000)
    AddBinBoundary(trType, 'PT', 'protonsalt', 1250)
    AddBinBoundary(trType, 'PT', 'protonsalt', 1500)
    AddBinBoundary(trType, 'PT', 'protonsalt', 2000)
    AddBinBoundary(trType, 'PT', 'protonsalt', 4000)
    AddBinBoundary(trType, 'PT', 'protonsalt', 7500)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'protonsalt', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'protonsalt',  60)
    AddBinBoundary(trType, 'nTracks', 'protonsalt', 120)
    AddBinBoundary(trType, 'nTracks', 'protonsalt', 180)
    AddBinBoundary(trType, 'nTracks', 'protonsalt', 240)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'Brunel_P',  'pions', 0, 160000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 4000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 12000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 44000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 56000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 64000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 75000)
    AddBinBoundary(trType, 'Brunel_P',  'pions', 90000)
    AddBinBoundary(trType, 'Brunel_P',  'pions',120000)

    # pt
    AddBinScheme(  trType, 'Brunel_PT', 'pions', 0, 20000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1100)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1200)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1300)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1400)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1600)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1700)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1800)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 1900)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 2250)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 2500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 2750)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 3000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 3500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 4500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 5000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 6250)
    AddBinBoundary(trType, 'Brunel_PT', 'pions', 7500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions',10000)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'pions', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'pions', 120)
    AddBinBoundary(trType, 'nTracks', 'pions', 180)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'Brunel_P',  'pions2', 0, 500000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 4000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 12000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 44000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 56000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 64000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 75000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2', 90000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2',120000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2',160000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2',250000)
    AddBinBoundary(trType, 'Brunel_P',  'pions2',350000)

    # pt
    AddBinScheme(  trType, 'Brunel_PT', 'pions2', 0, 25000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1100)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1200)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1300)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1400)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1600)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1700)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1800)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 1900)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 2250)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 2500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 2750)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 3000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 3500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 4500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 5000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 6250)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2', 7500)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2',10000)
    AddBinBoundary(trType, 'Brunel_PT', 'pions2',15000)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'pions2', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'pions2', 120)
    AddBinBoundary(trType, 'nTracks', 'pions2', 180)


for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'Brunel_P',  'electrons', 0, 160000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 4000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 12000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 44000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 56000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 64000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 75000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons', 90000)
    AddBinBoundary(trType, 'Brunel_P',  'electrons',120000)

    # pt
    AddBinScheme(  trType, 'Brunel_PT', 'electrons', 0, 20000)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1100)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1200)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1300)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1400)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1600)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1700)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1800)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 1900)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 2250)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 2500)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 2750)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 3000)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 3500)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 4500)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 5000)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 6250)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons', 7500)
    AddBinBoundary(trType, 'Brunel_PT', 'electrons',10000)

    # nTracks
    AddBinScheme(  trType, 'nTracks', 'electrons', 0, 500)
    AddBinBoundary(trType, 'nTracks', 'electrons', 120)
    AddBinBoundary(trType, 'nTracks', 'electrons', 180)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'Brunel_P',  'protonsAsMu', 0, 160000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 60000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu', 80000)
    AddBinBoundary(trType, 'Brunel_P',  'protonsAsMu',120000)

    # pt
    AddBinScheme(  trType, 'Brunel_PT', 'protonsAsMu', 0, 20000)
    AddBinBoundary(trType, 'Brunel_PT', 'protonsAsMu', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'protonsAsMu', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'protonsAsMu', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'protonsAsMu', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'protonsAsMu', 7500)

for trType in GetPartTypes():
    # momentum
    AddBinScheme(  trType, 'Brunel_P',  'misIDAsMu', 0, 160000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 8000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 16000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 20000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 24000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 28000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 32000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 36000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 40000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 50000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 60000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu', 80000)
    AddBinBoundary(trType, 'Brunel_P',  'misIDAsMu',120000)

    # pt
    AddBinScheme(  trType, 'Brunel_PT', 'misIDAsMu', 0, 20000)
    AddBinBoundary(trType, 'Brunel_PT', 'misIDAsMu', 1000)
    AddBinBoundary(trType, 'Brunel_PT', 'misIDAsMu', 1500)
    AddBinBoundary(trType, 'Brunel_PT', 'misIDAsMu', 2000)
    AddBinBoundary(trType, 'Brunel_PT', 'misIDAsMu', 4000)
    AddBinBoundary(trType, 'Brunel_PT', 'misIDAsMu', 7500)

