/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOB2KLL
#define ROOB2KLL

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooB2Kll : public RooAbsPdf {
public:
  RooB2Kll() {} ; 
  RooB2Kll(const char *name, const char *title,
                  RooAbsReal& _cosTheta,
                  RooAbsReal& _G000,
                  RooAbsReal& _G001,
                  RooAbsReal& _G002,
                  RooAbsReal& _G003,
                  RooAbsReal& _G004,
                  RooAbsReal& _a,
                  RooAbsReal& _b
                  );
  RooB2Kll(const RooB2Kll& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooB2Kll(*this,newname); }
  inline virtual ~RooB2Kll() { }

protected:

  RooRealProxy cosTheta ;
  RooRealProxy G000 ;
  RooRealProxy G001 ;
  RooRealProxy G002 ;
  RooRealProxy G003 ;
  RooRealProxy G004 ;
  RooRealProxy a ;
  RooRealProxy b ;
  
  Double_t evaluate() const ;

private:
  
  //ClassDef(RooB2Kll,1) // Your description goes here...
};
 
#endif
