{
	gROOT->ProcessLine(".L lhcbStyle.C");
	lhcbStyle();
	gStyle->SetPalette(1,0);
	const Int_t NRGBs = 5;
	const Int_t NCont = 255;
	Double_t stops[NRGBs] = { 0.00, 0.34, 0.61, 0.84, 1.00};
	Double_t red[NRGBs]   = { 0.00, 0.00, 0.87, 1.00, 0.51};
	Double_t green[NRGBs] = { 0.00, 0.81, 1.00, 0.20, 0.00};
	Double_t blue[NRGBs]  = { 0.51, 1.00, 0.12, 0.00, 0.00};
	TColor::CreateGradientColorTable(NRGBs, stops, red, green, blue, NCont);
	gStyle->SetNumberContours(NCont);
	gStyle->SetOptStat(0000);

	TFile* f = TFile::Open("hists/trkNew_sq10_all.root");
	TH2D* eff = (TH2D*)f->Get("efficiency");
	TH2D* errp = (TH2D*)f->Get("errorHi");
	TH2D* errm = (TH2D*)f->Get("errorLo");
	TH2D* errppc = errp->Clone("errorHiPc");
	TH2D* errmpc = errm->Clone("errorLoPc");

	TFile* f1 = TFile::Open("hists/trk_sq10_Bd_errStat_asym.root");
	TH2D* errstatp = (TH2D*)f1->Get("errorHi");
	TH2D* errstatm = (TH2D*)f1->Get("errorLo");
	TH2D* errstatppc = errstatp->Clone("errorStatHiPc");
	TH2D* errstatmpc = errstatm->Clone("errorStatLoPc");

	TFile* f2 = TFile::Open("hists/trk_sq10_Bd_errToy_asym.root");
	TH2D* errtabp = (TH2D*)f2->Get("errorHi");
	TH2D* errtabm = (TH2D*)f2->Get("errorLo");
	TH2D* errtabppc = errtabp->Clone("errorTabHiPc");
	TH2D* errtabmpc = errtabm->Clone("errorTabLoPc");

	TFile* f3 = TFile::Open("hists/trk_sq_Bd_effs.root");
	TH2D* effpi  = (TH2D*)f3->Get("pi");
	TH2D* effk   = (TH2D*)f3->Get("K");
	TH2D* effdpi = (TH2D*)f3->Get("D0pi");
	TH2D* effdk  = (TH2D*)f3->Get("D0K");

	TFile* f4 = TFile::Open("ratio2012S20.root");
	TH2D* Ratio  = (TH2D*)f4->Get("Ratio");

	errppc->Scale(100.);
	errppc->Divide(eff);
	errmpc->Scale(100.);
	errmpc->Divide(eff);
	errstatppc->Scale(100.);
	errstatppc->Divide(eff);
	errstatmpc->Scale(100.);
	errstatmpc->Divide(eff);
	errtabppc->Scale(100.);
	errtabppc->Divide(eff);
	errtabmpc->Scale(100.);
	errtabmpc->Divide(eff);

	TCanvas * canvas = new TCanvas("c2","c2");
	eff->SetLabelFont(62,"x");
	eff->SetLabelFont(62,"y");
	eff->SetTitleFont(62,"x");
	eff->SetTitleFont(62,"y");
	eff->SetTitleSize(0.06,"x");
	eff->SetTitleSize(0.06,"y");
	eff->SetLabelSize(0.05,"x");
	eff->SetLabelSize(0.05,"y");
	eff->SetXTitle("m'");
	eff->SetYTitle("#theta'");
	eff->GetZaxis()->SetRangeUser(1.02,1.06);
	canvas->SetRightMargin(0.17);
	eff->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_eff.pdf");
	eff->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_eff_nolabel.pdf");

	effpi->SetLabelFont(62,"x");
	effpi->SetLabelFont(62,"y");
	effpi->SetTitleFont(62,"x");
	effpi->SetTitleFont(62,"y");
	effpi->SetTitleSize(0.06,"x");
	effpi->SetTitleSize(0.06,"y");
	effpi->SetLabelSize(0.05,"x");
	effpi->SetLabelSize(0.05,"y");
	effpi->SetXTitle("m'");
	effpi->SetYTitle("#theta'");
	effpi->GetZaxis()->SetRangeUser(0.98,1.06);
	canvas->SetRightMargin(0.17);
	effpi->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_eff_pi.pdf");
	effpi->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_eff_pi_nolabel.pdf");

	effk->SetLabelFont(62,"x");
	effk->SetLabelFont(62,"y");
	effk->SetTitleFont(62,"x");
	effk->SetTitleFont(62,"y");
	effk->SetTitleSize(0.06,"x");
	effk->SetTitleSize(0.06,"y");
	effk->SetLabelSize(0.05,"x");
	effk->SetLabelSize(0.05,"y");
	effk->SetXTitle("m'");
	effk->SetYTitle("#theta'");
	effk->GetZaxis()->SetRangeUser(0.98,1.06);
	canvas->SetRightMargin(0.17);
	effk->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_eff_k.pdf");
	effk->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_eff_k_nolabel.pdf");

	effdpi->SetLabelFont(62,"x");
	effdpi->SetLabelFont(62,"y");
	effdpi->SetTitleFont(62,"x");
	effdpi->SetTitleFont(62,"y");
	effdpi->SetTitleSize(0.06,"x");
	effdpi->SetTitleSize(0.06,"y");
	effdpi->SetLabelSize(0.05,"x");
	effdpi->SetLabelSize(0.05,"y");
	effdpi->SetXTitle("m'");
	effdpi->SetYTitle("#theta'");
	effdpi->GetZaxis()->SetRangeUser(0.98,1.06);
	canvas->SetRightMargin(0.17);
	effdpi->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_eff_d0pi.pdf");
	effdpi->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_eff_d0pi_nolabel.pdf");

	effdk->SetLabelFont(62,"x");
	effdk->SetLabelFont(62,"y");
	effdk->SetTitleFont(62,"x");
	effdk->SetTitleFont(62,"y");
	effdk->SetTitleSize(0.06,"x");
	effdk->SetTitleSize(0.06,"y");
	effdk->SetLabelSize(0.05,"x");
	effdk->SetLabelSize(0.05,"y");
	effdk->SetXTitle("m'");
	effdk->SetYTitle("#theta'");
	effdk->GetZaxis()->SetRangeUser(0.98,1.06);
	canvas->SetRightMargin(0.17);
	effdk->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_eff_d0k.pdf");
	effdk->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_eff_d0k_nolabel.pdf");

	canvas->SetLogx();

	gStyle->SetTextFont(62);

	Ratio->SetLabelFont(62,"x");
	Ratio->SetLabelFont(62,"y");
	Ratio->SetTitleFont(62,"x");
	Ratio->SetTitleFont(62,"y");
	Ratio->SetTitleSize(0.06,"x");
	Ratio->SetTitleSize(0.06,"y");
	Ratio->SetLabelSize(0.05,"x");
	Ratio->SetLabelSize(0.05,"y");
	Ratio->SetXTitle("#it{p} [GeV/#it{c}]");
	Ratio->SetYTitle("#eta");
	Ratio->SetTitleOffset(1.1,"X");
	canvas->SetRightMargin(0.17);
	Ratio->Draw("colz");
	canvas->SaveAs("tracking.pdf");

	canvas->SetLogx(0);

	gStyle->SetPaintTextFormat("0.2f %%");
	
	gStyle->SetTextFont(132);
	gStyle->SetTextSize(0.06);

	errp->SetLabelFont(62,"x");
	errp->SetLabelFont(62,"y");
	errp->SetTitleFont(62,"x");
	errp->SetTitleFont(62,"y");
	errp->SetTitleSize(0.06,"x");
	errp->SetTitleSize(0.06,"y");
	errp->SetLabelSize(0.05,"x");
	errp->SetLabelSize(0.05,"y");
	errp->SetXTitle("m'");
	errp->SetYTitle("#theta'");
	canvas->SetRightMargin(0.17);
	errp->Draw("colz");
	errppc->Draw("text30same");
	canvas->SaveAs("../latex/figs/trk_errp.pdf");

	errm->SetLabelFont(62,"x");
	errm->SetLabelFont(62,"y");
	errm->SetTitleFont(62,"x");
	errm->SetTitleFont(62,"y");
	errm->SetTitleSize(0.06,"x");
	errm->SetTitleSize(0.06,"y");
	errm->SetLabelSize(0.05,"x");
	errm->SetLabelSize(0.05,"y");
	errm->SetXTitle("m'");
	errm->SetYTitle("#theta'");
	canvas->SetRightMargin(0.17);
	errm->Draw("colz");
	errmpc->Draw("text30same");
	canvas->SaveAs("../latex/figs/trk_errm.pdf");

	errstatp->SetLabelFont(62,"x");
	errstatp->SetLabelFont(62,"y");
	errstatp->SetTitleFont(62,"x");
	errstatp->SetTitleFont(62,"y");
	errstatp->SetTitleSize(0.06,"x");
	errstatp->SetTitleSize(0.06,"y");
	errstatp->SetLabelSize(0.05,"x");
	errstatp->SetLabelSize(0.05,"y");
	errstatp->SetXTitle("m'");
	errstatp->SetYTitle("#theta'");
	canvas->SetRightMargin(0.17);
	errstatp->Draw("colz");
	errstatppc->Draw("text30same");
	canvas->SaveAs("../latex/figs/trk_errpStats.pdf");

	errstatm->SetLabelFont(62,"x");
	errstatm->SetLabelFont(62,"y");
	errstatm->SetTitleFont(62,"x");
	errstatm->SetTitleFont(62,"y");
	errstatm->SetTitleSize(0.06,"x");
	errstatm->SetTitleSize(0.06,"y");
	errstatm->SetLabelSize(0.05,"x");
	errstatm->SetLabelSize(0.05,"y");
	errstatm->SetXTitle("m'");
	errstatm->SetYTitle("#theta'");
	canvas->SetRightMargin(0.17);
	errstatm->Draw("colz");
	errstatmpc->Draw("text30same");
	canvas->SaveAs("../latex/figs/trk_errmStats.pdf");

	errtabp->SetLabelFont(62,"x");
	errtabp->SetLabelFont(62,"y");
	errtabp->SetTitleFont(62,"x");
	errtabp->SetTitleFont(62,"y");
	errtabp->SetTitleSize(0.06,"x");
	errtabp->SetTitleSize(0.06,"y");
	errtabp->SetLabelSize(0.05,"x");
	errtabp->SetLabelSize(0.05,"y");
	errtabp->SetXTitle("m'");
	errtabp->SetYTitle("#theta'");
	canvas->SetRightMargin(0.17);
	errtabp->Draw("colz");
	errtabppc->Draw("text30same");
	canvas->SaveAs("../latex/figs/trk_errpTable.pdf");

	errtabm->SetLabelFont(62,"x");
	errtabm->SetLabelFont(62,"y");
	errtabm->SetTitleFont(62,"x");
	errtabm->SetTitleFont(62,"y");
	errtabm->SetTitleSize(0.06,"x");
	errtabm->SetTitleSize(0.06,"y");
	errtabm->SetLabelSize(0.05,"x");
	errtabm->SetLabelSize(0.05,"y");
	errtabm->SetXTitle("m'");
	errtabm->SetYTitle("#theta'");
	canvas->SetRightMargin(0.17);
	errtabm->Draw("colz");
	errtabmpc->Draw("text30same");
	canvas->SaveAs("../latex/figs/trk_errmTable.pdf");

	errppc->Scale(0.01);
	errmpc->Scale(0.01);
	errstatppc->Scale(0.01);
	errstatmpc->Scale(0.01);
	errtabppc->Scale(0.01);
	errtabmpc->Scale(0.01);

	gStyle->SetPaintTextFormat("g");

	errppc->SetLabelFont(62,"x");
	errppc->SetLabelFont(62,"y");
	errppc->SetTitleFont(62,"x");
	errppc->SetTitleFont(62,"y");
	errppc->SetTitleSize(0.06,"x");
	errppc->SetTitleSize(0.06,"y");
	errppc->SetLabelSize(0.05,"x");
	errppc->SetLabelSize(0.05,"y");
	errppc->SetXTitle("m'");
	errppc->SetYTitle("#theta'");
	errppc->GetZaxis()->SetRangeUser(0.002,0.013);
	canvas->SetRightMargin(0.17);
	errppc->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_errp_frac.pdf");
	errppc->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_errp_frac_nolabel.pdf");

	errmpc->SetLabelFont(62,"x");
	errmpc->SetLabelFont(62,"y");
	errmpc->SetTitleFont(62,"x");
	errmpc->SetTitleFont(62,"y");
	errmpc->SetTitleSize(0.06,"x");
	errmpc->SetTitleSize(0.06,"y");
	errmpc->SetLabelSize(0.05,"x");
	errmpc->SetLabelSize(0.05,"y");
	errmpc->SetXTitle("m'");
	errmpc->SetYTitle("#theta'");
	errmpc->GetZaxis()->SetRangeUser(0.002,0.013);
	canvas->SetRightMargin(0.17);
	errmpc->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_errm_frac.pdf");
	errmpc->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_errm_frac_nolabel.pdf");

	errstatppc->SetLabelFont(62,"x");
	errstatppc->SetLabelFont(62,"y");
	errstatppc->SetTitleFont(62,"x");
	errstatppc->SetTitleFont(62,"y");
	errstatppc->SetTitleSize(0.06,"x");
	errstatppc->SetTitleSize(0.06,"y");
	errstatppc->SetLabelSize(0.05,"x");
	errstatppc->SetLabelSize(0.05,"y");
	errstatppc->SetXTitle("m'");
	errstatppc->SetYTitle("#theta'");
	errstatppc->GetZaxis()->SetRangeUser(0.0015,0.004);
	canvas->SetRightMargin(0.17);
	errstatppc->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_errpStat_frac.pdf");
	errstatppc->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_errpStat_frac_nolabel.pdf");

	errstatmpc->SetLabelFont(62,"x");
	errstatmpc->SetLabelFont(62,"y");
	errstatmpc->SetTitleFont(62,"x");
	errstatmpc->SetTitleFont(62,"y");
	errstatmpc->SetTitleSize(0.06,"x");
	errstatmpc->SetTitleSize(0.06,"y");
	errstatmpc->SetLabelSize(0.05,"x");
	errstatmpc->SetLabelSize(0.05,"y");
	errstatmpc->SetXTitle("m'");
	errstatmpc->SetYTitle("#theta'");
	errstatmpc->GetZaxis()->SetRangeUser(0.0015,0.004);
	canvas->SetRightMargin(0.17);
	errstatmpc->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_errmStat_frac.pdf");
	errstatmpc->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_errmStat_frac_nolabel.pdf");

	errtabppc->SetLabelFont(62,"x");
	errtabppc->SetLabelFont(62,"y");
	errtabppc->SetTitleFont(62,"x");
	errtabppc->SetTitleFont(62,"y");
	errtabppc->SetTitleSize(0.06,"x");
	errtabppc->SetTitleSize(0.06,"y");
	errtabppc->SetLabelSize(0.05,"x");
	errtabppc->SetLabelSize(0.05,"y");
	errtabppc->SetXTitle("m'");
	errtabppc->SetYTitle("#theta'");
	errtabppc->GetZaxis()->SetRangeUser(0.002,0.013);
	canvas->SetRightMargin(0.17);
	errtabppc->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_errpTable_frac.pdf");
	errtabppc->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_errpTable_frac_nolabel.pdf");

	errtabmpc->SetLabelFont(62,"x");
	errtabmpc->SetLabelFont(62,"y");
	errtabmpc->SetTitleFont(62,"x");
	errtabmpc->SetTitleFont(62,"y");
	errtabmpc->SetTitleSize(0.06,"x");
	errtabmpc->SetTitleSize(0.06,"y");
	errtabmpc->SetLabelSize(0.05,"x");
	errtabmpc->SetLabelSize(0.05,"y");
	errtabmpc->SetXTitle("m'");
	errtabmpc->SetYTitle("#theta'");
	errtabmpc->GetZaxis()->SetRangeUser(0.002,0.013);
	canvas->SetRightMargin(0.17);
	errtabmpc->Draw("colztext30");
	canvas->SaveAs("../latex/figs/trk_errmTable_frac.pdf");
	errtabmpc->Draw("colz");
	canvas->SaveAs("../latex/figs/trk_errmTable_frac_nolabel.pdf");

   std::cout << errppc->GetBinContent(errppc->GetMinimumBin()) << "-" << errppc->GetBinContent(errppc->GetMaximumBin()) << std::endl;
   std::cout << errmpc->GetBinContent(errmpc->GetMinimumBin()) << "-" << errmpc->GetBinContent(errmpc->GetMaximumBin()) << std::endl;
}
